# apiVersion: 1
# datasources:
#   - name: websocket - weatherflow-collector
#     type: golioth-websocket-datasource
#     typeName: WebSocket API
#     typeLogoUrl: public/plugins/golioth-websocket-datasource/img/logo.svg
#     # access: proxy
#     basicAuth: false
#     isDefault: false
#     jsonData:
#       host: 'ws://weatherflow-collector.maxo99.com:6789'
#     readOnly: false
